baseURL = "https://minhhuy0211.github.io/"
languageCode = "vi-vn"
title = "Nguyá»…n Trá»‹nh Minh Huy"
theme = "PaperMod"

[params]
    defaultTheme = "light"
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true
    author = "Nguyá»…n Trá»‹nh Minh Huy"
    description = "Portfolio & Blog chia sáº» kiáº¿n thá»©c Láº­p trÃ¬nh máº¡ng, Java Backend, JavaScript."
customCSS = ["css/style.css"]
    # --- PROFILE ---
    [params.profileMode]
        enabled = true
        title = "Hi, I'm Nguyá»…n Trá»‹nh Minh Huy ðŸ‘‹"
        subtitle = "Java Backend Developer | Network Engineering Student"
        imageUrl = "AVT.jpg"
        imageWidth = 150
        imageHeight = 150

# --- MENU ---
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Trang chá»§"
        url = "/"
        weight = 10

    [[menu.main]]
        identifier = "about"
        name = "Giá»›i thiá»‡u"
        url = "/about/"
        weight = 20

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts/"
        weight = 30
[[menu.main]]
        identifier = "certificates"
        name = "Chá»©ng chá»‰"
        url = "/certificates/"
        weight = 35
    [[menu.main]]
        identifier = "contact"
        name = "LiÃªn há»‡"
        url = "/contact/"
        weight = 40

# --- MARKDOWN ---
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# --- FIX CSS GITHUB PAGES ---
canonifyURLs = true
relativeURLs = false

# --- BUILD ---
[build]
    writeStats = false
    noJSConfigInAssets = true

[minify]
    disableCSS = false
    disableHTML = false
    disableJS = false
    disableJSON = false
    disableSVG = false
    disableXML = false
    minifyOutput = false
